### ISSUE TITLE
Missing SIGIR and SIGVRST

### ISSUE THREAD

**Issue by pranaygp** [acm-uiuc/groot-groups-store#1]
We should add information for SIGVRST and SIGIR (we may be missing more)

```yaml
- name: SIGVRST
  description: Special Interest Group for Virtual, Augmented, and Mixed Reality
  chairs: Abhishek Modi
  meetingTime: '5:00 PM' 
  meetingDay: Thursday
  meetingLoc: Siebel 4405
  site: 'http://www.acm.illinois.edu/sigvrst'
  members: []
  email: 'VRST-l@acm.illinois.edu'

- name: SIGIR
  description: Special Interest Group for Information Retrieval
  chairs: John Doe
  meetingTime: 'X:XX AM|PM' 
  meetingDay: Weekday
  meetingLoc: Siebel XXXX
  site: 'http://www.acm.illinois.edu/sigir'
  members: []
  email: 'SIGIR-l@acm.illinois.edu'
```
